create_clock -period 40.00 -name clkref [get_ports {CLK25}]
create_clock -period 100 -name clk0 [get_registers {counter0[4]}]
create_clock -period 100 -name clk1 [get_registers {counter1[4]}]
create_clock -period 100 -name clk2 [get_registers {counter2[4]}]
create_clock -period 100 -name clk3 [get_registers {counter3[4]}]
create_clock -period 100 -name clk4 [get_registers {counter4[4]}]
create_clock -period 100 -name clk5 [get_registers {counter5[4]}]
create_clock -period 100 -name clk6 [get_registers {counter6[4]}]
create_clock -period 100 -name clk7 [get_registers {counter7[4]}]
derive_pll_clocks
